### ISSUE TITLE
Tooltips and .buttons .has-addons

### ISSUE THREAD

**Issue by sinrise** [buefy/buefy#1115]
### Overview of the problem

**Buefy** version: [0.6.7]
**Vuejs** version: [2.5.7]
**OS/Browser**: Windows 10/Chrome

### Description

Using the b-tooltip container breaks the border rounding and negative margins for buttons inside .buttons.has-addons container.

### Steps to reproduce

1. Create a div with a class of .buttons and .has-addons
2. add button elements.
3. wrap each button element in it's own b-tooltip tag

### Expected behavior

Buttons retain negative 1px margin and corner rounding defined with .buttons.has-addon

### Actual behavior

Buttons are styled like individual buttons

**Comment by sylvainpolletvillard** [comment]
Workaround: add these custom css rules

```css
.field.has-addons .b-tooltip:not(:first-child):not(:last-child) .button,
.field.has-addons .b-tooltip:not(:first-child):not(:last-child) .input,
.field.has-addons .b-tooltip:not(:first-child):not(:last-child) .select select,
.field.has-addons .b-tooltip:not(:first-child):not(:last-child) .taginput .taginput-container.is-focusable,
.taginput .field.has-addons .b-tooltip:not(:first-child):not(:last-child) .taginput-container.is-focusable{
    border-radius:0
}

.field.has-addons .b-tooltip:first-child:not(:only-child) .button,
.field.has-addons .b-tooltip:first-child:not(:only-child) .input,
.field.has-addons .b-tooltip:first-child:not(:only-child) .select select,
.field.has-addons .b-tooltip:first-child:not(:only-child) .taginput .taginput-container.is-focusable,
.taginput .field.has-addons .b-tooltip:first-child:not(:only-child) .taginput-container.is-focusable{
    border-bottom-right-radius:0;border-top-right-radius:0
}

.field.has-addons .b-tooltip:last-child:not(:only-child) .button,
.field.has-addons .b-tooltip:last-child:not(:only-child) .input,
.field.has-addons .b-tooltip:last-child:not(:only-child) .select select,
.field.has-addons .b-tooltip:last-child:not(:only-child) .taginput .taginput-container.is-focusable,
.taginput .field.has-addons .b-tooltip:last-child:not(:only-child) .taginput-container.is-focusable{
    border-bottom-left-radius:0;border-top-left-radius:0
}
```
