### ISSUE TITLE
Weird element selection for upload component on IOS

### ISSUE THREAD

**Issue by agcty** [buefy/buefy#1524]
### Overview of the problem

**Buefy** version:0.7.8
**Vuejs** version: 2.6.10
**OS/Browser**: iOS 12.3.1

### Description

When trying to click on an upload component (specifically, the drag and drop one) devices running on iOS 12.3.1 select a weird item. On Safari itself this just doesn't look good, however, when using Buefy in conjunction with @nuxtjs/pwa, clicking the upload component won't do anything which is a serious issue.

### Steps to reproduce

Open https://buefy.org/documentation/upload on an iOS device (I'm using an iPhone X) and try to click the drag and drop upload component.

### Expected behavior
The browser selects the whole element, rather than a single line inside the component and opens a file dialog.

### Actual behavior
In normal Safari, when clicking on an upload component, it selects a single line within and then opens a file dialog. When clicking on the upload component within an installed PWA, it selects a single line and then does nothing, there is no file dialog.

In normal Safari:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12101091/60505511-27fe2180-9cc4-11e9-8464-c00924aa1b62.gif)

As a PWA (with normal website at the end to see contrast)

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/12101091/60505964-18330d00-9cc5-11e9-9f5e-31c2b64184ff.gif)

**Comment by jtommy** [comment]
@agcty Unfortunately I don't have a iOS device to test it but i've just updated something in upload style. 
Are you able to test current dev branch ?

**Comment by agcty** [comment]
I'd be happy to test and contribute! Is there any documentation on how to do so?

**Comment by jtommy** [comment]
@agcty i changed only scss, you might try to use https://github.com/buefy/buefy/blob/dev/src/scss/components/_upload.scss in your project

**Comment by agcty** [comment]
Ok so I did this and it seems to work on both pwa and normal safari. I tested this on an iPad running 12.3.1 - same as the iPhone I tested it with earlier. I'm gonna try it out with an iPhone as soon as I can, although I believe the error should be resolved.

```scss
@charset "utf-8";
// 1. Import the initial variables
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";

// 2. Set own initial variables
@import url('https://fonts.googleapis.com/css?family=Nunito');
@import "./variables";

// 3. Add new color variables to the color map.
@import "~bulma/sass/utilities/derived-variables";
$addColors: (
  "accent":($accent, $white)
);
$colors: map-merge($colors, $addColors);

// 4. Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
// 5. Import bulma extensions
@import '~bulma-divider';


.upload {
  position: relative;
  display: inline-flex;
  input[type=file] {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      opacity: 0;
      outline: none;
      cursor: pointer;
      &.file-draggable {
          z-index: -1;
      }
  }
  .upload-draggable {
      cursor: pointer;
      padding: 0.25em;
      border: 1px dashed $grey-light;
      border-radius: $radius-large;
      &.is-disabled {
          opacity: 0.5;
          cursor: not-allowed;
      }
      &.is-loading {
          position: relative;
          pointer-events: none;
          opacity: 0.5;
          &:after {
              @include loader;
              top: 0;
              left: calc(50% - 1.5em);
              width: 3em;
              height: 3em;
              border-width: 0.25em;
          }
      }
      &:hover,
      &.is-hovered {
          @each $name, $pair in $colors {
              $color: nth($pair, 1);
              &.is-#{$name} {
                  border-color: $color;
                  background: rgba($color, 0.05);
              }
          }
      }
  }
}
```

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/12101091/60591946-d0cd7f00-9d9f-11e9-8183-11de0ab6f58d.gif)
