### ISSUE TITLE
How override word spacing on autocomplete items.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [buefy/buefy#1978]
![изображение](https://user-images.githubusercontent.com/9306996/68801107-d358b300-0674-11ea-9de8-af3399d0666b.png)

```
<b-autocomplete>
            <div class="media words-overflow" slot-scope="props">....</div>
<b-autocomplete>
```

```css
.words-overflow {
    word-wrap: anywhere !important;
    word-break: break-all !important;
    white-space: unset !important;
}
```

Doesn't help. How we should disable white-spacing on parent **a** tag div?

Also heres no refs for this slot with a tag or other stuff.
