### ISSUE TITLE
add option to disable navbar collapse

### ISSUE THREAD

**Issue by wookoouk** [buefy/buefy#2131]
### Description

I often have navbars with 1-2 items so collapsing on mobile is often overkill for me, linkline.io (`https://inkline.io/docs/components/navbar`) has the option `:collapse="false"` to allow you to disable the collapsing of the navbar when in mobile proportions.

### Why Buefy need this feature

It is another option that would be helpful with multiple scenarios when you do not wish for the navbar to collapse.

**Comment by jtommy** [comment]
@wookoouk did you try https://github.com/jgthms/bulma/issues/1445#issuecomment-443308954 ?

**Comment by wookoouk** [comment]
Yes, I saw that,  it isn't what I asked for but I guess it's all I have if you will not allow me to implement ~`:collapse="false"`
Thanks

**Comment by jtommy** [comment]
@wookoouk you are free to make a PR if you want to add it in order to change default Bulma behaviour

**Comment by fabiofdsantos** [comment]
@doomedramen @jtommy 
I think using `$navbar-breakpoint: 0;` isn't enough. For example, if you are using `is-primary` type, you will also need to hack the `background-color` of `.navbar-menu`. Maybe the issue could be re-opened for discussion, otherwise the alternative is avoid using `b-navbar` for certain scenarios (which is not a drama ofc).

**Comment by akicho8** [comment]
`$navbar-breakpoint: 0`
`b-navbar(wrapper-class="container" spaced)`

This will not be the menu when the mobile.
But, margin of spaced does not disappear in the mobile when it was.
I am troubled. 😭

**Comment by doomedramen** [comment]
This is still an issue for me, and I am still using vanilla bulma to get around it for navbars

**Comment by rzeiler** [comment]
I fix this issue with css overwrite
```css
.navbar-brand {
  display: none;
}

.navbar-menu {
  display: flex;
  flex-grow: 1;
  box-shadow: none;
}
.navbar-start,
.navbar-end {
  align-items: stretch;
  display: flex;
  flex-grow: 1;
}
.navbar-end {
  justify-content: flex-end;
}
````
