### ISSUE TITLE
.modal

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#2344]
### Overview of the problem

**Buefy** version: [0.8.13]
**OS/Browser**: chrome

### Description
 correct bulma css  [bulma demo](https://bulma.io/documentation/components/modal/)
``` css
.modal-content,
.modal-card {
  margin: 0 20px;
  max-height: calc(100vh - 160px);
  overflow: auto;
  position: relative;
  width: 100%;
}

@media screen and (min-width: 769px), print {
  .modal-content,
  .modal-card {
    margin: 0 auto;
    max-height: calc(100vh - 40px);
    width: 640px;
  }
}
```
error buefy css
```css
.modal-content,
.modal-card {
  margin: 0 20px;
  max-height: calc(100vh - 160px);
  overflow: auto;
  position: relative;
  width: 100%;
}

@media screen and (min-width: 769px), print {
  .modal-content,
  .modal-card {
    margin: 0 auto;
    max-height: calc(100vh - 40px);
    width: 640px;
  }
}

.modal .modal-content { // The CSS weight is too high 
  width: 100%;
}
```
