### ISSUE TITLE
update bulma to 0.8.x please

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#2410]
```css
 // version 0.8
.card {
  background-color: white;
  box-shadow: 0 0.5em 1em -0.125em rgba(10, 10, 10, 0.1), 0 0px 0 1px rgba(10, 10, 10, 0.02);
  color: #4a4a4a;
  max-width: 100%;
  position: relative;
}
```

```css
//  0.7
.card{
  background-color: white;
     box-shadow: 0 2px 3px rgba(10, 10, 10, 0.1), 0 0 0 1px rgba(10, 10, 10, 0.1); 
    color: #666666;
    max-width: 100%;
    position: relative;
}
  
```
box-shadow is inconsistence
