### ISSUE TITLE
b-checkbox margins cause bad experience in mobile

### ISSUE THREAD

**Issue by fabiofdsantos** [buefy/buefy#2459]
### Overview of the problem

Buefy version: 0.8.17
OS/Browser: macOS / Safari

### Description

Current `.b-checkbox.checkbox + .checkbox` margins are causing some unexpected breaks.

### Steps to reproduce

1. Use multiple `b-checkbox` elements.
2. Go to mobile version.

### Expected behavior

![image](https://user-images.githubusercontent.com/8303937/80724912-4a3a1900-8afa-11ea-89c7-efc67d3b3bfc.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/8303937/80694431-6aeb7a00-8acc-11ea-8cc2-634cd7a41a1d.png)

**Comment by fabiofdsantos** [comment]
Just a quick tip to override existing styles:
```scss
.b-checkbox.checkbox {
  &:not(:last-child) {
    margin-right: 1em;
  }
}
.b-checkbox.checkbox + .checkbox {
  margin-left: 0;
}
```
