### ISSUE TITLE
No option to select all rows in mobile version of Table component with “checkable” option

### ISSUE THREAD

**Issue by c-myers1** [buefy/buefy#2479]
### Description

When you set checkable on a table, there is a checkbox on the header to select all rows. When you reduce the viewport to columnar display, this option disappears.

### Why Buefy need this feature

There is a far greater distance to scroll down in a columnar version so it’s more convenient to be able to select all at once on header

**Comment by jtommy** [comment]
@c-myers1 on mobile there isn't a common header using mobile cards.
Do you have any proposals about it ? Where would you like to see the checkbox?

**Comment by c-myers1** [comment]
There is a common header where the table sorting bar appears. A check-all box should appear there somewhere. Perhaps a line on its own.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by subins2000** [comment]
I added this to `_table.scss` to get this result :
```css
@mixin table-cards {
    thead {
        th {
            display: none;
        }
        .checkbox-cell {
            display: block;
            width: 100%;
            text-align: right;
        }
    }
    ...rest.of.it...
```
If this result is alright, I'll send a PR. Btw, @jtommy, Buefy is awesome. Good work! :heart: 
![image](https://user-images.githubusercontent.com/2305675/86792107-c8311800-c087-11ea-8307-2335053614d9.png)
