### ISSUE TITLE
b-table's b-checkbox 100% broken without css imported

### ISSUE THREAD

**Issue by dgattey** [buefy/buefy#2529]
### Overview of the problem

**Buefy** version: 0.18.18 and 0.8.19
**Vuejs** version: 2.5.22 and 2.6.11 (both tested)
**OS/Browser**: Chrome, Firefox on macOS

### Description

Unless you import buefy's css file (`buefy/dist/buefy.css`), a `b-table` with `checkable=true` doesn't reactively emit `@check` except when clicking on the checkbox in the table header. In other words, checkboxes are broken on tables unless you import the CSS. This is because these lines have the effect of 1) *hiding* the native input and putting a different element there instead that acts as the click target.

Buefy should always work without importing styles. Totally breaks checkboxes on tables here.

```scss
.b-checkbox.checkbox {
  outline: none;
  display: inline-flex;
  align-items: center;
}
```
and
```scss
.b-checkbox.checkbox input[type=checkbox] {
  position: absolute;
  left: 0;
  opacity: 0;
  outline: none;
  z-index: -1;
}

.b-checkbox.checkbox input[type=checkbox] + .check {
  width: 1.25em;
  height: 1.25em;
  flex-shrink: 0;
  border-radius: 4px;
  border: 2px solid #7a7a7a;
  transition: background 150ms ease-out;
  background: transparent;
}
```

### Steps to reproduce

1. Import and use any b-table with any of the supported methods
2. Set `checkable=true` and `checked-rows=checkedRowsArray` and `@check=someMethod`
3. Make sure Buefy's CSS isn't imported
4. Try clicking on any of the checkboxes in any of the rows. While the checkbox itself shows a check or not, `checkedRowsArray` never gets updated, and `someMethod` never gets called.

### Expected behavior

1. `@check` should trigger reactively without styles imported
2. `checked-rows` should update without styles imported (both with and without the `sync` modifier)

### Actual behavior

Neither one of those things happened - checking the checkboxes only changed the UI, not the backing data.

Thanks for taking a look!
