### ISSUE TITLE
Don't extend .input directly

### ISSUE THREAD

**Issue by Zephyrrus** [buefy/buefy#2667]
### Description

Would it be possible to not extend the .input class directly in the tag input component? https://github.com/buefy/buefy/blob/dd26c4809011f547175d5635cfe4b06a76f3d461/src/scss/components/_taginput.scss#L7

This leads to issues and a lot of headaches when a user is trying to stylize all the inputs with `.input` class but not the tag inputs themselves.

### Why Buefy need this feature

Because right now buefy's scss will take into consideration every `.input` declaration in scss, leading to a lot of side-effects when trying to only redefine the inputs without applying those styles to the tag input.

Right now the solution we had to go with was creating a custom class for our input, define our custom styles there, then add an additional class to each b-input. 
This doesn't really make sense because we want to apply our custom styles to every input (but not tag inputs, since the default style is fine for them).

One solution to this problem would be using placeholder selectors, as per the documentation https://sass-lang.com/documentation/at-rules/extend#placeholder-selectors

Thank you!

**Comment by jtommy** [comment]
Can you make an example?

**Comment by Zephyrrus** [comment]
For example, if I'm trying to stylize a few components like

```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";

.input,
.textarea,
.select select {
    height: 3rem;
    font-family: 'Segoe UI', 'Roboto';
}
```

because of the scss `@extend .input`, the css will become

```css
/* everything from the imports will be here */

.input,
.taginput .taginput-container.is-focusable,
.textarea,
.select select {
    height: 3rem;
    font-family: 'Segoe UI', 'Roboto';
}
```

In this case, the `.taginput` will be stylized even if we don't want this to happen. 

Because `@extend` is global, if the buefy scss get imported anywhere in the project's styles, it will append `.taginput .taginput-container.is-focusable` after every `.input` selector.
