### ISSUE TITLE
Unexpected behavior of datepicker component inside modals

### ISSUE THREAD

**Issue by wanxe** [buefy/buefy#292]
### Overview of the problem

**Buefy** version: 0.5.1
**Vuejs** version: 2.4.2
**OS/Browser**: OSX Sierra Chrome

### Description

When use the datepicker inside little modals, the datepicker doesn't float. 

### Steps to reproduce
1. Create any component within a modal.
2. Use the b-datepicker
3. Try to open :D

### Expected behavior

Datepicker respect the z-indexes and floats overall.

### Actual behavior
Datepicker is hidden because the modal doesn't have the sufficient height.

**Comment by jtommy** [comment]
@wanxe Datepicker uses a dropdown component and there is an open issue https://github.com/jgthms/bulma/issues/936

**Comment by wanxe** [comment]
@jtommy Oh sorry, nice to know :) 
Thanks.

**Comment by donaldinos** [comment]
I have same issue .. plz. exist some fix ?
<img width="505" alt="screen shot 2017-11-27 at 13 34 05" src="https://user-images.githubusercontent.com/376663/33269110-d587c30c-d37f-11e7-8dd5-dd28a2d4ba09.png">

**Comment by wanxe** [comment]
I've solved with that 
```css 
body.modal-open {
  overflow: hidden;
}
```

**Comment by donaldinos** [comment]
Thank you for your reply .. but it not works me :(
What of kind object is exactly your modal-open ? 
This code is from parent or in child component ?

**Comment by wanxe** [comment]
Can you try that?
```css
.modal .animation-content .modal-card {
  overflow: visible !important;
}

.modal-card-body {
  overflow: visible !important;
}
```
