### ISSUE TITLE
Support inline SVG icons

### ISSUE THREAD

**Issue by dword-design** [buefy/buefy#3155]
### Description

Currently the icon system depends on icon fonts. Meaning you set a class and that class sets a special font family that contains the respective icons.

This approach has its pros and cons. On the pro side is the ease of use because you can just set a class and you have an icon. On the con side is the bundle size and the page loading time. Explicitly setting the icon set leads to dependencies between the components and the app config.

A different approach is to directly render inline SVGs instead. There are webpack loaders that allow to load SVG files and use them as components. Then you can do something like this:

```code
<template>
  <mdi-rss aria-hidden="true" class="icon" />
</template>

<script>
import MdiRss from '@mdi/svg/svg/rss.svg'

export default {
  components: {
    MdiRss,
  },
}
</script>
```

This is currently not working with Buefy because the `b-icon` component requires the icon property to be a string, and then constructs css classes and passes them to the underlying `defaultIconComponent`. You have to create the icons yourself without using `b-icon` (see above). Also, you cannot use `b-button` and the dialog system, which implicitly use `b-icon`. A better approach would be to leave the class creation to the `defaultIconComponent` and to widen up the allowed icon types to objects and strings, so we can pass the SVG icon through. Then you could do things like this:
```code
<template>
  <div>
    <b-icon :icon="MdiRss" />
    <b-button :icon-left="MdiRss" />
  </div>
</template>

<script>
import MdiRss from '@mdi/svg/svg/rss.svg'

export default {
  computed: {
    MdiRss: () => MdiRss,
  },
}
</script>
```

I've successfully used the approach in [this project](https://feedbutler.app/) by mainly directly using the bulma classes and would love use it within Buefy.

### Why Buefy need this feature

It allows to use the common technique of inline SVG icons with Buefy to decrease the bundle size and remove the dependency between the component and the app config.

Looking forward to your thoughts. I'm also open to contributing a PR if people like the idea.

**Comment by zonque** [comment]
This limitation is in fact a real issue for deployments on systems with limited storage resources. The MDI web font is some orders of magnitude larger than my application, and there is currently no alternative to the (discouraged) way of embedding all icons through the font.

@dword-design maybe a PR is worth a shot to demonstrate how things would look like?

**Comment by johnpuddephatt** [comment]
I too have been bothered by this due to the size of the MDI font, to the extent that I started exploring creating my own replacement icon component... and at this point I realised it's not difficult to use inline SVG icons through the existing Buefy icon component!

1. Configure Buefy to use an icon component that we'll create in step 2.
```
import SvgIcon from './SvgIcon'
Vue.use(Buefy, {
  defaultIconPack: null,
  defaultIconComponent: SvgIcon
});
```
2. Create the SvgIcon component referenced above. (e.g. ./SvgIcon.vue). The example below uses [Vue Feather Icons](https://github.com/egoist/vue-feather-icons) but it should be possible with others. This component receives your icon name, converts it from kebab-case to camelCase and loads the right icon component. The CSS at the end is necessary to override some existing CSS. You'll need to import all icons you're using. I've just added two in this example – ArrowRightIcon and CheckIcon.
```css
<template>
  <component :is="iconName"></component>
</template>
<script>
import { ArrowRightIcon, CheckIcon } from 'vue-feather-icons'
export default {
  components: {
    ArrowRightIcon,
    CheckIcon
  },
  props: ['icon','size'],
  computed: {
    iconName: function() {
      return `${ this.icon[1].replace(/-./g, x=>x.toUpperCase()[1]).replace(/\b\w/g, c => c. toUpperCase()) }Icon`;
    }
  },
}
</script>

<style lang="scss">
  .icon svg {
    stroke-width: 2 !important;
    fill: none !important;
  }
</style>
```
3. Use as you normally would in Buefy, e.g. `<b-icon icon="arrow-right">` or `<b-button icon-left="check">`
