### ISSUE TITLE
the info dropdown  of navbar is invalid at https://buefy.org/documentation/start/ 

### ISSUE THREAD

**Issue by Valar103769** [buefy/buefy#3160]
reason is `:hover` dont set `visibleity:visible`
```css
.navbar .navbar-dropdown.is-boxed{
  visibility:hidden
}
```
