### ISSUE TITLE
Add delay to tooltip

### ISSUE THREAD

**Issue by SamUndefined** [buefy/buefy#594]
Other vue-tooltip plugins and jQuery, for example, allow the developer to add a delay which controls the amount of time the user must hover an element before its tooltip pops up. Perhaps this feature could be part of Buefy, maybe as a prop in the form of milliseconds:

```
<b-tooltip
    label="My delayed tool tip"
    position="is-right"
    delay="1000"
    >
```

By the way, thanks for this excellent component package!

**Comment by gierloff** [comment]
Great idea!

**Comment by laegeloen** [comment]
Any news on adding delay to tooltips? :) please?

**Comment by emanuelmutschlechner** [comment]
@laegeloen 

I've used a simple CSS workaround using the `transition-delay` property. It works fine if you want to change it globally. 

```css
.tooltip:not([data-label=""]):hover:before, 
.tooltip:not([data-label=""]):hover:after {
    transition-delay: 1s;
}
```

To apply a delay to a specific tooltip you could just add a custom class and set that on `<b-tooltip>`.
```css
.tooltip.is-slow:not([data-label=""]):hover:before, 
.tooltip.is-slow:not([data-label=""]):hover:after {
    transition-delay: 3s;
}
```

> Demo
https://codepen.io/anon/pen/XxjxRX
