### ISSUE TITLE
Use bulimia variables inside style template ?

### ISSUE THREAD

**Issue by MatthD** [buefy/buefy#991]
Hi ,

What is the best way to use bulma variables inside vue style template ?

I already imported buefy into my general .scss, & I can import it in any .vue file , but is this the best solution ?

// main.scss
```scss
@import '_variables';
@import '_header';
@import '~bulma/sass/utilities/_all';
body {
  background-color: $mainBackgroundColor;
  color: $mainFontColor;
  font-size: 35px;
  h1 {
    font-size: 75px;
  }
}

// Import Bulma and Buefy styles
@import '~bulma';
@import '~buefy/src/scss/buefy';
```

// .../parrot.vue
```html
<template>
  <section class="parrotSection">
    <input 
      v-model="message" 
      placeholder="change-me"
    >
    <p>Le message est : {{ message | Upper }}</p>
  </section>
</template>
 
 <style scoped lang="scss">
  @import '~bulma/bulma.sass'; // ok I can import, but .. I already imported .scss globally isn't it ?
  $code-family: "Helvetica";
  #tets{
    text-align: center !important;
  }
  .parrotSection{
    background: lightgreen;
    p{
      color: $orange;
    }
  }
</style>
```
